name: Pack and push library

on:
  push:
    branches: [ "main" ]

env:
  NUGET_URL: https://git.codvoc.com/api/packages/blazorsaas/nuget/index.json
  SOURCE_PATH: 'latest.zip'
  DESTINATION_PATH: 'components/latest.zip'
  R2_BUCKET: 'blazorsaas'

jobs:
  build-pack-and-archive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.100-rc.1.24452.12

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build

      - name: Pack
        run: dotnet pack -o:package

      - name: Push generated packages
        run: dotnet nuget push ./package/*.nupkg  --source ${{ env.NUGET_URL }} --api-key ${{ secrets.PACKAGE_API_KEY }}

      - name: Create archive
        run: |
          git archive -o ${{ env.SOURCE_PATH }} HEAD

      - name: Upload archive to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_R2_API_KEY }}
          command: r2 object put ${{ env.R2_BUCKET }}/${{ env.DESTINATION_PATH }} --file=${{ env.SOURCE_PATH }}