name: Pack and push library

on:
  push:
    branches: [ "main" ]

env:
  NUGET_URL: https://git.codvoc.com/api/packages/blazorsaas/nuget/index.json

jobs:
  pack:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.0-rc.1.24452.12

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build

      - name: Pack
        run: dotnet pack -o:package

      - name: Push generated packages
        run: dotnet nuget push ./package/*.nupkg  --source ${{ env.NUGET_URL }} --api-key ${{ secrets.PACKAGE_API_KEY }}
